### PR TITLE
Added auditlog_hr_timesheet and auditlog_project modules

### PR DESCRIPTION
**Pull request by ByteMeAsap**
Simple modules to record deletion for project,task and timesheet to help syncing with external apps faster

### CODE REVIEW

**Review by tarteo — COMMENTED** [review]
I'm not in favor to make changes to Odoo to facilitate a mobile app.

**Comment by ByteMeAsap** [comment]
> I'm not in favor to make changes to Odoo to facilitate a mobile app.

Ok, but can we have a generic module to just allow read access to internal users to audit logs? We would then add it in the description on the mobile app page to set these rules up for faster syncing?

**Comment by tarteo** [comment]
I don't know what they use projects and timesheets for. Most customers don't have many (thousands) of ongoing projects so I can't imagine syncing them will be any problem. Timesheets could have thousands of records however then I would implement a pagination mechanism in the app instead. But I don't know the functionality of the mobile app. :wink:

**Comment by ByteMeAsap** [comment]
> I don't know what they use projects and timesheets for. Most customers don't have many (thousands) of ongoing projects so I can't imagine syncing them will be any problem. Timesheets could have thousands of records however then I would implement a pagination mechanism in the app instead. But I don't know the functionality of the mobile app. 😉

Well the app is basically made for timesheets and task syncing.Here is the link for the app which has detailed description of what the module does- https://open-store.io/app/timemanagementapp.synconics

The problem scenario was only for the records being deleted , others (for writes and creations)can be tracked using write_date.

Although I agree with what you say. So we can basically add everything about setting up the auditlogs on the description page for the app including providing read users to internal users

**Comment by andreschenkels** [comment]
I would say that you don't need extra modules to retrieve deleted items or new items. This can easily be done with some simple calls. You shouldn't need extra modules for that. @ByteMeAsap

**Pull request closed without merging**
